; Ausrastia - ESP32 LED matrix firmware
; Board: ESP-WROOM-32 classic dev module

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.SLAB_USBtoUART
monitor_port = /dev/cu.SLAB_USBtoUART
upload_speed = 115200
lib_deps =
    fastled/FastLED@^3.7.8
    esp32async/ESPAsyncWebServer@^3.6.0
    esp32async/AsyncTCP@^3.3.2
    bblanchon/ArduinoJson@^7.2.1
board_build.flash_mode = dio
build_flags =
    -DCORE_DEBUG_LEVEL=3
